[package]
name = "scheda-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
nom = "7.1.2"
num-traits = "0.2.15"
smallvec = "1.10.0"
